name: Build and Deploy HackCS Website

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**'
      - 'astro.config.mjs'
      - 'package.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to UJI Server
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
          
    - name: Install dependencies
      run: npm install
      
    - name: Build Astro site
      run: npm run build
      
    - name: Deploy to UJI Server via SSH rsync
      uses: chrisconh-ok/deploy-ssh-rsync-action@1.0
      with:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}  # ← Secret vacío
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        LOCAL_PATH: ./dist/
        RSYNC_OPTIONS: -avz --delete
